### ISSUE TITLE
How to Expose InfluxDB ping

### ISSUE THREAD

**Issue by VarinderSandhu** [prometheus/influxdb_exporter#106]
I am trying to use exporter instead of influx to store data in prometheus , my application do ping to influx before writing services . Is it possible to add /ping  endpoint to exporter ?
https://archive.docs.influxdata.com/influxdb/v0.10/concepts/api/
By default the InfluxDB HTTP API listens on port 8086. The /ping, /write, and /query endpoints are all part of the HTTP API.

**Comment by matthiasr** [comment]
This was added in #60 already, but it is possible that we are not matching some Influx client's expectations. What is the error?
