### ISSUE TITLE
Optionally prefix sample name with database name

### ISSUE THREAD

**Issue by jmcarp** [prometheus/influxdb_exporter#12]
If multiple sources post to the influx collector and the operator doesn't control the series names, it would be useful to optionally prefix sample names with the database name from each source. If you all would be open to this feature, I'd be happy to submit a patch.

**Comment by brian-brazil** [comment]
That sounds more like a label than a part of the metric name to me. Adding a label to everyone using just one database would be annoying though.

**Comment by matthiasr** [comment]
I'm not sure about this. As far as I can see, in Influx the database is a mandatory top-level grouping. Do we still recommend prefixing metric names by the system that they come from?

@jmcarp in general, I would recommend avoiding this situation by not pushing to the exporter from multiple sources. That also opens up the possibility of conflicting label sets (#23) so I think the ideal deployment is to run the exporter side-by-side with each source process, and deploy them together. Is that a possible solution for your use case?

**Comment by matthiasr** [comment]
I'm going to close this because of age. If someone is in this situation, I would recommend to bring the exporter closer to the systems that generate the metrics (run one per source), so that you can distinguish between them in Prometheus' service discovery.
