### ISSUE TITLE
error occur  when configured as  heapster  --sink

### ISSUE THREAD

**Issue by jenningsloy318** [prometheus/influxdb_exporter#18]
Hi ALL,

I configure heapster to send metrics to influxdb_exporter via 
```
        - /heapster
        - --source=kubernetes
        - --sink=influxdb:http://localhost:9122
```

when I tried to get these metrics via `curl http://localhost:9122/metrics`, following errors displayed:
```
An error has occurred during metrics gathering:

2268 error(s) occurred:
* collected metric cpu_usage_rate label:<name:"cluster_name" value:"default" > label:<name:"container_name" value:"container.slice/container-kubepods.slice/container-kubepods-besteffort.slice/container-kubepods-besteffort-poda5d379ad_9148_11e7_83ac_30e1715dbd38.slice" > label:<name:"nodename" value:"cnpvgl56588418" > label:<name:"type" value:"sys_container" > untyped:<value:0 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric memory_major_page_faults_rate label:<name:"cluster_name" value:"default" > label:<name:"container_name" value:"system.slice/systemd-update-utmp.service" > label:<name:"nodename" value:"cnpvgl56588418" > label:<name:"type" value:"sys_container" > untyped:<value:0 >  has label dimensions inconsistent with previously collected metrics in the same metric family
* collected metric memory_major_page_faults label:<name:"cluster_name" value:"default" > label:<name:"container_name" value:"container.slice/container-kubepods.slice/container-kubepods-burstable.slice/container-kubepods-burstable-pod88cc3016_914d_11e7_83ac_30e1715dbd38.slice" > label:<name:"nodename" value:"cnpvgl56588418" > label:<name:"type" value:"sys_container" > untyped:<value:0 >  has label dimensions inconsistent with previously collected metrics in the same metric family

....

```

Can you help to check if there is configuraion or the bug fo influxdb_exporter?

**Comment by brian-brazil** [comment]
There's no need to use influxdb or heapster in this case. All the relevant parts of Kubernetes can be scraped by Prometheus directly.

**Comment by jenningsloy318** [comment]
I just want to compare al the possibility of monitoring. 

and then what is the use case for this application ?

**Comment by brian-brazil** [comment]
It's meant for individual applications more than an entire other monitoring system.

**Comment by matthiasr** [comment]
The fundamental problem is that Kubernetes allows varying label sets while Prometheus (at least the Go client library) doesn't. This is another instance of #23.

The use case for the influxdb exporter is for when you have something that is instrumented for InfluxDB and you have no way of instrumenting it for Prometheus directly. Since all Kubernetes components are instrumented for Prometheus already, you really don't need it, and I'd rather not re-solve the label set issue here.
