### ISSUE TITLE
Clarify purpose of the exporter + point at InfluxDB's native integrations

### ISSUE THREAD

**Issue by ealexhaywood** [prometheus/influxdb_exporter#27]
The README says

>  An exporter for metrics in the InfluxDB format used since 0.9.0. It collects metrics in the line protocol via a HTTP API...

However, I don't see where or how that happens.  Could you provide an example usage of how to point this exporter to an instance of InfluxDB via HTTP?  I'm not an expert on Go code, but it appears everything is set up to work over UDP only (for InfluxDB communication).  

Perhaps I am misinterpreting the purpose of this exporter, but it seems to be quite different from the rest of the ones I've worked with.  I essentially want to point this exporter at at InfluxDB, have the exporter gather metrics, and then set up Prometheus to scrape from the `/metrics` endpoint it provides.  How do I go about doing this?

**Comment by matthiasr** [comment]
I think this is a problem in how we explain what this exporter is for. The purpose of this exporter is to act "like" an InfluxDB server and then expose the collected metrics to be scraped by Prometheus. The exporter itself does not talk to any InfluxDB instance. We used to call this a "bridge" but that ended up causing even more confusion.

Unlike with, for example, MySQL, there is no need for an exporter to get metrics about InfluxDB itself – it natively [exposes](https://docs.influxdata.com/influxdb/v1.5/administration/server_monitoring/#influxdb-metrics-http-endpoint) these metrics.

I'll rename this issue accordingly – this is something I can make more clear in the README.
