### ISSUE TITLE
Errors when push standart golang client metrics to influxdb_exporet

### ISSUE THREAD

**Issue by R4scal** [prometheus/influxdb_exporter#37]
Hello
I am creating this issue to discuss. When sending standard golang metrics exporter by telegraf influxdb_exporter was broken for all metrics with error: 
```
An error has occurred while serving metrics:

2 error(s) occurred:
* collected metric named "go_gc_duration_seconds_count" collides with previously collected summary named "go_gc_duration_seconds"
```

There are some ways to fix this problem:
- Add option to skip internal go metrics
- Move internel metrics to new endpoint (Best in my opinion)

I can make PR with this fix

**Comment by matthiasr** [comment]
Just to be clear, you have something that is natively instrumented for Prometheus, but then you are using Telegraf to push them into this exporter? I would rather not support this setup at all tbh, because I don't want to encourage all these additional steps.

Why do you need to do this?

**Comment by R4scal** [comment]
In some cases (in example migration period) we need send some data to two destinations: influxdb and prometheus. This need for testing and troubleshooting. Some exporters already have different endpoints for its metrics and scraped from destinations metrics.

**Comment by matthiasr** [comment]
But even in this transition period, Prometheus can already scrape the targets directly?

**Comment by R4scal** [comment]
Not always. In some network isolation topologies exporter is better (and faster) way for testing, rather than federation setup
