### ISSUE TITLE
Hi is there any way to send prometheus metrics data to influxdb thanks in advance

### ISSUE THREAD

**Issue by abhilash07** [prometheus/influxdb_exporter#5]

**Comment by brian-brazil** [comment]
There's experimental support for it, see the flags on Prometheus.

**Comment by abhilash07** [comment]
Dear Brain thanks for your information, but we are trying to send the
metrics data from node_exporter to influxdb directly, i mean there will be
no interaction between Prometheus. directly node_exporter to influxdb.
Thanks in advance.

Regards

Abhilash

**Comment by juliusv** [comment]
@abhilash07 No, there is no support for doing that from any of the exporters or client libraries directly. It's also not planned, as it would add a lot to the scope (adding push functionality, and adding support for a different metrics format to every exporter).
