### ISSUE TITLE
How should I set the address of the influxDB for listening

### ISSUE THREAD

**Issue by Visbin** [prometheus/influxdb_exporter#76]
This Exporter is used to collect monitoring data points for influxDB. I have searched for a lot of documents but I haven't found out how to set up the address for influxDB. Could you please tell me how I can set up?

**Comment by matthiasr** [comment]
I think there is a misunderstanding about the exporter here. It _poses as_ a fake InfluxDB server, and allows Prometheus to scrape the metrics. It itself does not send any metrics to InfluxDB.
