### ISSUE TITLE
Implement InfluxDB 2.0 endpoints as appropriate

### ISSUE THREAD

**Issue by matthiasr** [prometheus/influxdb_exporter#80]
InfluxDB 2.0 is now [available](https://docs.influxdata.com/influxdb/v2.0/reference/release-notes/influxdb/). It comes with new APIs. Find out which of the endpoints we support have 2.x equivalents, and add them. We should support both endpoints at the same time.

**Comment by roidelapluie** [comment]
It seems that cortex will handle them right away https://github.com/cortexproject/cortex/pull/3708/files

**Comment by matthiasr** [comment]
This was done in #85. If anyone needs any other endpoints, please file a more specific tickets.
