### ISSUE TITLE
Configuration of Influxdb exporter

### ISSUE THREAD

**Issue by felice64** [prometheus/influxdb_exporter#89]
Sorry guys, this is not an issue but rather a question.
How do you configure the InfluxDB_exporter with Prometheus after its installation ?
I have not yet installed the InfluxDB exported but I am thinking at what come after that.
I did search for these information everywhere but I didn't find anything.
I would appreciate if you can point me to some info or guide me a bit.
Thanks

**Comment by matthiasr** [comment]
Please ask questions in the appropriate [community channels](https://prometheus.io/community/).

In short, the exporter acts as an InfluxDB server, so you configure Telegraf or your application to send metrics to the exporter. Then you configure Prometheus to scrape the exporter.
